### ISSUE TITLE
[Bug]: Issues with add-on YAML on k8s 1.24

### ISSUE THREAD

**Issue by danielbichuetti** [linode/rancher-ui-driver-linode#24]
### Expected Behavior

Add-ons should get installed during deployment of unmanaged cluster.

### Actual Behavior

The jobs that Rancher launches fail because of changes to the Kubernetes API. The v1beta1 versions have been replaced with the v1 version. 

### Steps to Reproduce

1. Provision a cluster using Rancher, following official Linode guide: https://www.linode.com/docs/guides/how-to-deploy-kubernetes-on-linode-with-rancher-2-x/#provision-a-cluster
2. Look for the logs of the rke-user-includes-addons-deploy-job-* pods.

### Error Output

clusterrole.rbac.authorization.k8s.io/external-attacher-role unchanged
clusterrolebinding.rbac.authorization.k8s.io/csi-controller-attacher-binding unchanged
clusterrole.rbac.authorization.k8s.io/external-snapshotter-role unchanged
clusterrolebinding.rbac.authorization.k8s.io/csi-controller-snapshotter-binding unchanged
storageclass.storage.k8s.io/linode-block-storage unchanged
statefulset.apps/csi-linode-controller unchanged
resource mapping not found for name: "csinodeinfos.csi.storage.k8s.io" namespace: "" from "/etc/config/rke-user-includes-addons.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
ensure CRDs are installed first
resource mapping not found for name: "csidrivers.csi.storage.k8s.io" namespace: "" from "/etc/config/rke-user-includes-addons.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
ensure CRDs are installed first
resource mapping not found for name: "linodebs.csi.linode.com" namespace: "" from "/etc/config/rke-user-includes-addons.yaml": no matches for kind "CSIDriver" in version "csi.storage.k8s.io/v1alpha1"
ensure CRDs are installed first
resource mapping not found for name: "csi-linode-node" namespace: "kube-system" from "/etc/config/rke-user-includes-addons.yaml": no matches for kind "DaemonSet" in version "extensions/v1beta1"
ensure CRDs are installed first
resource mapping not found for name: "external-dns" namespace: "kube-system" from "/etc/config/rke-user-includes-addons.yaml": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1"
ensure CRDs are installed first
resource mapping not found for name: "external-dns-viewer" namespace: "kube-system" from "/etc/config/rke-user-includes-addons.yaml": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1"
ensure CRDs are installed first
resource mapping not found for name: "external-dns" namespace: "kube-system" from "/etc/config/rke-user-includes-addons.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"

**Comment by lgarber-akamai** [comment]
Thanks for the report @danielbichuetti!

I've put up a PR (#25) to upgrade the manifest to use currently supported API versions.

If you'd like to test out these changes, you can follow the guide mentioned above and replace the segment

```
addons_include:
    - https://linode.github.io/rancher-ui-driver-linode/releases/v0.3.0/linode-addons.yml
```

with

```
addons_include:
    - https://raw.githubusercontent.com/linode/rancher-ui-driver-linode/1073aef7f2f0165705e879810c9b93e5a71ab524/releases/v0.6.0/linode-addons.yml
```
