### ISSUE TITLE
The root password field should include a placeholder and complexity validation

### ISSUE THREAD

**Issue by displague** [linode/rancher-ui-driver-linode#3]
https://kubernetes.slack.com/archives/CD4B15LUR/p1550243383019000?thread_ts=1550242523.014700&cid=CD4B15LUR

```
[ERROR] NodeController c-92s8b/m-6tjt4 [node-controller] failed with : Error creating machine: Error in driver during machine creation: [400] [root_pass] Password must contain at least 2 of these 4 character classes: lowercase letters, uppercase letters, numbers, and punctuation
```

The default behavior of docker-machine-driver-linode is to auto-generate 50 bytes of crypto/rand data for use as the root password. This root password is disposed of in this case (it would be usable for authentication if known).

Root authentication to nodes is still possible using the SSH key available through the download keys feature in Rancher and through the "Authorized Users" parameter (taking advantage of Linode's SSH Key features) if provided in the node template.

**Comment by lgarber-akamai** [comment]
Closing this issue out since we don't plan on adding any new functionality to this project.
