### ISSUE TITLE
Why can't I create a nanode instance?

### ISSUE THREAD

**Issue by kingmatusevich** [linode/rancher-ui-driver-linode#5]
there are plenty of cases where I could choose to use a nanode instance, and it should be up to me anyway.

**Comment by displague** [comment]
@kingmatusevich Fair enough.  I was trying to restrict the bad experience options.  You'll notice that the distribution images that simply do not work (with the Rancher install scripts) have been removed.  1GB of RAM is below the documented minimum requirements and in practice tends not to work well (or at all).

* https://rancher.com/docs/rancher/v2.x/en/installation/requirements/
* https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/hardware.md#example-hardware-configurations

The Nanode may be ok for the control-plane, etcd, or worker in some cases.  If K3s is eventually exposed through the Rancher installer, the Nanode option should prove even more viable.

Depending on where you look, you can find other recommendations:

* https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/production/#hardware-requirements-2

If we can confirm that the Nanode works for some (or all) of these roles, let's enable it.

I don't recall adding any extra validation, so modifying the `<select>` value (through the browser's Inspector) to `g6-nanode-1` should make it easy enough to prove that this size is viable.

**Comment by kingmatusevich** [comment]
my clusters are generally very small, since I don't really need a lot of scale or computing power, but I do need a more-than-average failure-resistant service, so I'd like to experiment with having many nanodes for certain roles rather than a couple bigger nodes. I will try your method and let you know how it works for me

**Comment by kingmatusevich** [comment]
It definitely works, if you want to enable it permanently.

**Comment by displague** [comment]
@kingmatusevich I think my suggestion doesn't actually work.  Can you verify that a Nanode was deployed and not a g6-standard-1?  (I attempted the steps above and ended up with a g6-standard-1).

You can verify this from the linode-cli, Cloud manager, or by the reported RAM of the node.

**Comment by kingmatusevich** [comment]
<img width="571" alt="Screen Shot 2019-03-16 at 15 38 53" src="https://user-images.githubusercontent.com/1448511/54479955-9dbbab80-4801-11e9-9202-39f0903c9666.png">
It deployed a nanode

**Comment by kingmatusevich** [comment]
What I did was add an extra select with the nanode value when I was setting up the template, and as you can see it worked for me.

**Comment by displague** [comment]
Well.. It works! 😆 This is included in the latest master, 4efe0f4

This is available in the same `v0.2.0` release URL.

![image](https://user-images.githubusercontent.com/317653/54842234-c6cbb880-4ca7-11e9-93f6-4543317baaa0.png)

![image](https://user-images.githubusercontent.com/317653/54842246-d3501100-4ca7-11e9-9d5c-241e8f12c2d5.png)
